### ISSUE TITLE
cf log-meta ordering and limits

### ISSUE THREAD

**Issue by bradylove** [cloudfoundry/log-cache-cli#13]
Every time you run `cf log-meta` the results are displayed in a different order and there is no sorting.

It would be nice to sort on one of the columns by default and have the option to sort on the other columns.

The results are also limited to 50 items prior to filtering application vs platform scope. So I only see a few platform source ids and the results are always different which does not seem very helpful.

**Comment by apoydence** [comment]
Per conversation with @ahevenor we implemented the feature without the flag to dictate which column to sort on. We figured if this was a necessary experience, we could add it later.
