### ISSUE TITLE
Envelope type filter is broken

### ISSUE THREAD

**Issue by kitemongerer** [cloudfoundry/log-cache-cli#15]
When I do a command like `cf tail <app name> --envelope-type=counter -n 100` I still see gauge metrics

**Comment by JohannaSmith** [comment]
@kitemongerer do you remember what commit the log cache cli plugin was built off of? Because I cannot replicate on master. If you rebuild the plugin and `cf install-plugin -f` it, do you still experience this?

**Comment by hdub2** [comment]
Just rebuilt and repro'd using e88374a22418a876d09608dc979c92df4fd80786. Happy to provide more if you want to see our env, etc.

**Comment by apoydence** [comment]
Per a conversation, it looks like this was occurring due to a breaking API change: `envelope_type` -> `envelope_types`. The CLI was trying the new API while the environment was servicing the old.
