### ISSUE TITLE
logcache help shows options incorrectly

### ISSUE THREAD

**Issue by kitemongerer** [cloudfoundry/log-cache-cli#16]
If you do a command like `cf tail --help` it will show options like `-json` but it should be `--json` (with two dashes). `cf tail -json` errors.

**Comment by bradylove** [comment]
@kitemongerer it appears this is happening because the CF CLI is displaying them with a single dash, however the package we are using for flags only supports double dash. 

We will either have to PR the CF CLI to make that configurable in some way or use another package to manage our CLI flags.

**Comment by bradylove** [comment]
That makes sense, we have had to do some odd things like that to get other things to display correctly.

**Comment by bradylove** [comment]
A fix for this has been pushed to master.
