### ISSUE TITLE
Request: publish pre-built binary versions of the log-cache CLI plugin for Linux and Mac OS X

### ISSUE THREAD

**Issue by emalm** [cloudfoundry/log-cache-cli#25]
I have greatly enjoyed using the log-cache CLI plugin against CF environments that have the log-cache components deployed. As a CF CLI user, though, I don't want to have to build the plugin executable from the Golang source, especially since the plugin has a lot of dependencies and the workflow in https://github.com/cloudfoundry/log-cache-cli#installing-plugin pulls them all at master via `go get` instead of vendoring them. Ideally, I'd prefer to get this plugin from the [CF-Community plugin repo](https://plugins.cloudfoundry.org/), but I would certainly be happy with 64-bit Linux and Mac OS X binaries published on the release in this GitHub repository.

**Comment by johannasmith** [comment]
Hey @emalm, we actually have a [story in our backlog](https://www.pivotaltracker.com/story/show/157092596) coming up soon to cut a `1.0` release for this cli that will have linux, darwin, and windows binaries available for download.

We also have a [story](https://www.pivotaltracker.com/story/show/156435980) to make it available through the community plugins.

**Comment by emalm** [comment]
Thanks @johannasmith, that's great!
