### ISSUE TITLE
log-meta should have option to sort by various columns

### ISSUE THREAD

**Issue by apoydence** [cloudfoundry/log-cache-cli#27]
It would be nice to be able to sort the output of log-meta based on specific columns (e.g., `expired`).

**Comment by johannasmith** [comment]
I would additionally consider it beneficial for default behavior to be "sort by `source_id`" because they currently return in a randomized order.

**Comment by apoydence** [comment]
It does currently sort by the `source_id`: see #13

**Comment by colins** [comment]
@apoydence sounds like you need to brush up on your awk and sort :)

**Comment by apoydence** [comment]
I'm going to reopen this issue.

An example use case is parity with `log-noise`:

Sorting by something like `expired` could give insight to operators which producer is overwhelming their system (much like `log-noise` does) without installing the noisy-neighbor-nozzle.

**Comment by toddboom** [comment]
Pretty sure this work is done with the `--sort-by` flag. Closing it out.
