### ISSUE TITLE
Support valid JSON objects in non-streaming contexts

### ISSUE THREAD

**Issue by jasonkeene** [cloudfoundry/log-cache-cli#28]
This doesn't work:

```
$ cf tail uaa -n 2 --json | python -m json.tool
Extra data: line 2 column 1 - line 3 column 1 (char 270 - 528)
```

I assume the bytes that come out of `tail` are streaming [line delimited JSON][line-delimited-json]. However, there is no reason to stream these objects. They could be encapsulated in a JSON array and compatibility would improve.

For instance this works:

```
$ echo "[" $(cf tail uaa -n 2 --json | paste -sd "," -) "]" | python -m json.tool
[
    {
        "gauge": {
            "metrics": {
                "vitals.vm.memory.committed": {}
            }
        },
        "sourceId": "uaa"
    },
    {
        "gauge": {
            "metrics": {
                "vitals.vm.memory.free": {}
            }
        },
        "sourceId": "uaa"
    }
]
```

[line-delimited-json]: https://en.wikipedia.org/wiki/JSON_streaming#Line-delimited_JSON

**Comment by toddboom** [comment]
This story has been accepted, closing it out.
