### ISSUE TITLE
JSON keys are different from --json and the API

### ISSUE THREAD

**Issue by jasonkeene** [cloudfoundry/log-cache-cli#29]
Keys that are multi-word such as `source_id` are represented with underscores in the API but actually show up as `sourceId` in the CLI when `--json` is provided.

This affects both the CF CLI plugin and the standalone log-cache CLI.

**Comment by jasonkeene** [comment]
This can be solved by providing the `json_name` option for each field name in the `.proto` files.

For example:

```
int64 source_id  = 1 [json_name="source_id"];
```

See [the spec][proto3-json].

[proto3-json]: https://developers.google.com/protocol-buffers/docs/proto3#json

**Comment by toddboom** [comment]
This story has been accepted, closing it out.
