### ISSUE TITLE
Unexpected status code 404

### ISSUE THREAD

**Issue by ashwithahn** [cloudfoundry/log-cache-cli#36]
Hi I Installed log-cache to enable log-cache for App Autoscaler. After installing getting below error, is the usage right?
>> cf log-meta --noise
Failed to read Meta information: unexpected status code 404

**Comment by toddboom** [comment]
@ashwithahn Can you tell us more about your CF deployment? How are you deploying Log Cache?

It seems like Log Cache may be missing, which could be the reason for the 404s. It's not yet GA in cf-deployment, so you'd need to add it with an ops file, such as:
https://github.com/cloudfoundry/cf-deployment/blob/master/operations/experimental/use-log-cache.yml

**Comment by ashwithahn** [comment]
This is resolved @toddboom . Thank you. I would like to close this

**Comment by mishrarajan** [comment]
Hi @toddboom 
facing the same issue, can you please share the file: 
https://github.com/cloudfoundry/cf-deployment/blob/master/operations/experimental/use-log-cache.yml.

**Comment by discordgr** [comment]
Hi @toddboom , i'm currently facing the same issue. But the github repo seems to have changed. Is the solution the same? If so, can you share the file?
