### ISSUE TITLE
Standalone installation instructions clarification

### ISSUE THREAD

**Issue by scottschulthess** [cloudfoundry/log-cache-cli#42]
Hello log-cache-cli folks! 

I tried running the script to install the standalone version of the plugin 

``` 
~ curl -sS https://raw.githubusercontent.com/cloudfoundry/log-cache-cli/develop/scripts/install.sh | bash
bash: line 8: /Users/$MY_HOMEDIR/build.sh: No such file or directory
```
It works fine if you first clone the log-cache-cli and cd into the /scripts directory -  can we update the install script to handle this or amend the instructions to specify you need to do this first? 

Thank you!

**Comment by johannaratliff** [comment]
Fixed.

**Comment by jtuchscherer** [comment]
@scottschulthess Thanks for reporting this. Let us know if you have any problems with the new instructions.
