### ISSUE TITLE
Bug Fix: Respect `--lines` when `--envelope-class` is passed through

### ISSUE THREAD

**Issue by johannaratliff** [cloudfoundry/log-cache-cli#46]
As a user of the cli,
I want to be able to request my last `n` envelopes of `envelope-class`. Currently, I can request `n` and then that batch gets filtered down by envelope-class. I would like to change this priority so I can see my last n logs, not my logs that existed in my last n nodes in the cache for that source_id.

Context in slack: https://pivotal.slack.com/archives/CBF2AU6A0/p1557946497068900

E.g.
```
cf tail flowspinner -n 100 | wc -l
     100

cf tail flowspinner -n 100 -c logs | wc -l
      88
```
I would want 
```
cf tail flowspinner -n 100 -c logs | wc -l
      100
```
/cc @kitemongerer

**Comment by ctlong** [comment]
@johannaratliff is this issue completed by cloudfoundry/log-cache#104?

**Comment by ctlong** [comment]
Closing based off the assumption that this request is complete. Please feel free to re-open if it's not.
