### ISSUE TITLE
log-cache CLI produces no output when user has access to many orgs

### ISSUE THREAD

**Issue by menicosia** [cloudfoundry/log-cache-cli#47]
I love the `log-cache` plugin, it does wonderful magic which gives devs self-service access.

Unfortunately, I have some special permissions on a very large foundation that we run (my CF user is something like ReadOnlyAdmin):

```
→ cf login -a api.SYSTEM-DOMAIN
API endpoint: api.SYSTEM-DOMAIN

Select an org (or press enter to skip):
There are too many options to display, please type in the name.

Org> dedicated-mysql-dev
Targeted org dedicated-mysql-dev

[...]
→ cf tail -f acceptDB
Retrieving logs for service acceptDB in org dev / space PM as mnicosia@pivotal.io...
[never responds]
```

**Comment by pianohacker** [comment]
We believe this is due to https://github.com/cloudfoundry/log-cache-release/issues/33; closing in favor of that issue.

(Sorry for the long delay in responding to you; there has been some turnover on the team in the past year.)
